/*
 * Copyright 2019, The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sechnick.mileage_autotracker.activetrip

import android.os.Bundle
import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.databinding.DataBindingUtil
import androidx.fragment.app.Fragment
import androidx.fragment.app.activityViewModels
import androidx.lifecycle.Observer
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.ViewModelStoreOwner
import androidx.navigation.fragment.findNavController
import com.sechnick.mileage_autotracker.R
import com.sechnick.mileage_autotracker.database.MileageDatabase
import com.sechnick.mileage_autotracker.databinding.FragmentActiveTripBinding
import com.sechnick.mileage_autotracker.triptracker.TripTrackerViewModel
import kotlinx.android.synthetic.main.fragment_active_trip.*

/**
 * Fragment that displays a list of clickable icons,
 * each representing a sleep quality rating.
 * Once the user taps an icon, the quality is set in the current sleepNight
 * and the database is updated.
 */
class ActiveTripFragment : Fragment() {

    val tripTrackerViewModel : TripTrackerViewModel by activityViewModels()

    /**
     * Called when the Fragment is ready to display content to the screen.
     *
     * This function uses DataBindingUtil to inflate R.layout.fragment_active_trip.
     *
     * It is also responsible for passing the [ActiveTripViewModel] to the
     * [FragmentSleepQualityBinding] generated by DataBinding. This will allow DataBinding
     * to use the [LiveData] on our ViewModel.
     */
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?,
                              savedInstanceState: Bundle?): View? {

        // Get a reference to the binding object and inflate the fragment views.
        val binding: FragmentActiveTripBinding = DataBindingUtil.inflate(
                inflater, R.layout.fragment_active_trip, container, false)

        val application = requireNotNull(this.activity).application
        val arguments = arguments?.let { ActiveTripFragmentArgs.fromBundle(it) }

        // Create an instance of the ViewModel Factory.
        val dataSource = MileageDatabase.getInstance(application).mileageDatabaseDao
        val viewModelFactory  = arguments?.recordedTripKey?.let { ActiveTripViewModelFactory(it, dataSource) } as ViewModelProvider.Factory

        // Get a reference to the ViewModel associated with this fragment.
        val activeTripViewModel =
                ViewModelProvider(
                        activity as ViewModelStoreOwner, viewModelFactory).get(ActiveTripViewModel::class.java)


//        tripTrackerViewModel =
//                ViewModelProvider(
//                        activity as ViewModelStoreOwner, viewModelFactory).get(TripTrackerViewModel::class.java)

        // To use the View Model with data binding, you have to explicitly
        // give the binding object a reference to it.
        binding.sleepQualityViewModel = activeTripViewModel

        binding.tripTrackerViewModel = tripTrackerViewModel

        // Add an Observer to the state variable for Navigating when a Quality icon is tapped.
        activeTripViewModel.navigateToSleepTracker.observe(viewLifecycleOwner, Observer {
            if (it == true) { // Observed state is true.
                this.findNavController().navigate(
                        ActiveTripFragmentDirections.actionSleepQualityFragmentToSleepTrackerFragment())
                // Reset state to make sure we only navigate once, even if the device
                // has a configuration change.
                activeTripViewModel.doneNavigating()
            }
        })

        // Add an Observer to the state variable for Navigating when a Quality icon is tapped.
        tripTrackerViewModel.navigateToSleepTracker.observe(viewLifecycleOwner, Observer {
            if (it == true) { // Observed state is true.
                this.findNavController().navigate(
                        ActiveTripFragmentDirections.actionSleepQualityFragmentToSleepTrackerFragment())
                // Reset state to make sure we only navigate once, even if the device
                // has a configuration change.
                tripTrackerViewModel.onTrackerNavigated()
            }
        })



        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        TripTrackerViewModel.myService.point.observe(viewLifecycleOwner, Observer {
            imageArrow.rotation = it.bearing
            Log.d("service live data", "bearing = "+it.bearing)
        })

//        imageArrow.setOnClickListener{
//            imageArrow.rotation = TripTrackerViewModel.myService.point.bearing
//        }

        //TODO add background worker to allow for updates to this?
        //imageArrow.rotation = TripTrackerViewModel.myService.currentPoint.bearing
    }
}
